### ISSUE TITLE
nombres componentes

### ISSUE THREAD

**Issue by holandes1969** [Phoneboard/Phoneboard#10]
algunos lay outs como por ejemplo el iPhone 8 no indican nombre del componente ni a que línea se pertenece.
solo indica donde tiene continuidad .

es algo complicado trabajar de esta manera porque no sabes si seria un capacitor o un filtro por ejemplo ni que línea estas comprobando.

doy como ejemplo el iPhone 8 pero hay algunos mas donde solo indican donde hacen conexión sin información adicional. 

te mando un saludo,

**Comment by holandes1969** [comment]
veo ahora que ya te lo han comentado en otro post.
disculpa por repetir

**Comment by guidopola** [comment]
Duplicate of #6
