### ISSUE TITLE
Net names

### ISSUE THREAD

**Issue by AppleSurgery** [Phoneboard/Phoneboard#12]
Hi,

Just it will be very usefull to add net names on the pads itself when You will zoom it then it will be a lot quicker to see what is the net name instead of hovering on it.

**Comment by moondeck** [comment]
When you click on a pad, it already shows you the net name, in the bottom bar.

**Comment by AppleSurgery** [comment]
To powiedz jest szansa że będzie opcja na MacOS? 
Kwestia że wszystkie linie widzę od razu ułatwia diagnozę płyty.
Jeszcze opcja płyty iphone 7 z intelem. 
Mam kanał na yt to mogę rozreklamować Twój soft 🙂
Co myślisz?
Pozdrawiam 
    	
    	

    	Regards,Damian
    
  




On Sat, Nov 24, 2018 at 7:25 PM +0000, "Olgierd Nowakowski" <notifications@github.com> wrote:












Yep.

**Comment by moondeck** [comment]
No idea, you could try running the Windows version in a Wine container (mentioned in #4 )

Phoneboard is not mine, its a project by @guidopola 
I am just a random guy from the internet that happens to both repair electronics and do programming/github/all that stuff.
