### ISSUE TITLE
Enter/Return Button in Search does not work

### ISSUE THREAD

**Issue by At-M** [Phoneboard/Phoneboard#2]
If you search something in the searchbar, you are able to click it (if it shows up of course) and it shows up on the schematic, if you press enter instead (tested on iphone6s, PP3V3_USB) it doesn't show up

If you've worked with the software a bit and then want to go back to the contact you've searched for at first (the one that is still in the searchbar) you need to remove a letter and press on the searchresult again. If you were able to just press enter, it saves some time :)

ps: I'm not a professional repairguy, just a guy who likes to test software, if you want me to stop, just tell me :D

**Comment by guidopola** [comment]
Thank you for the feedback!, every report/question are welcome, I'm not a professional repair either :+1: .
Yeah the enter key event aren't handled, i'll mark it as an enhancement ;)

**Comment by At-M** [comment]
okay :)
If you want some more audience, check out the Group 
"Introduction to Micro Soldering, Micro BGA & Component Level Diagnostics" on Facebook, that's where I found this software, and that's where a lot of repairguys post info too

**Comment by guidopola** [comment]
Fixed in v1.1.0
