### ISSUE TITLE
open BRD

### ISSUE THREAD

**Issue by holandes1969** [Phoneboard/Phoneboard#20]
como estas?
muy bueno la actualización,  con las lineas de los tornillos.

tambien veo ahora la pestaña  open BRD.

podrias aclarar para que sirve ese pestaña?

gracias

**Comment by guidopola** [comment]
Es para abrir archivos de formato brd, en gral lo utilizan los tecnicos que reparan laptops

**Comment by guidopola** [comment]
PD: La proxima vez que tengas una duda contactame por [facebook](https://www.facebook.com/app.phoneboard)
