### ISSUE TITLE
update

### ISSUE THREAD

**Issue by clemy84** [Phoneboard/Phoneboard#24]
can't update to the new version i'm on windows 10 latest build doesn't open thanks.

**Comment by guidopola** [comment]
Hi Stephen, could you elaborate more? the installer doesn't open or the app?

**Comment by clemy84** [comment]
Hi the installer doesn’t open to install the app I’ve downloaded it three times v1.00 installs perfect but can’t install v1.31 i think  it is it’s the latest version out version one says update I tried it and it won’t open to update.


Sent from Yahoo Mail for iPhone


On Monday, December 10, 2018, 11:50 pm, Guido Pola <notifications@github.com> wrote:


Hi Stephen, could you elaborate more? the installer doesn't open or the app?

**Comment by clemy84** [comment]
Hi it’s the installer that doesn’t open I’ve tried it 3 times. v1.00 says update I’ve tried it that way still the same it doesn’t open to install the update either it’s rhe latest version.

**Comment by guidopola** [comment]
ok, does it shows any error or something? I'm on linux atm, I will switch to windows to test but i didn't get any report about installing issues

**Comment by clemy84** [comment]
Nope it just spins like it’s loading then stops and that’s it doesn’t say any error it just doesn’t load or attempt to load.

**Comment by guidopola** [comment]
The installer is working fine on my box, did you tried to running with administrator privileges?

**Comment by guidopola** [comment]
i can upload it zipped if you want

**Comment by clemy84** [comment]
I tried running it it with administration privileges nothing and please that would be great thank you

**Comment by guidopola** [comment]
https://github.com/Phoneboard/Phoneboard/releases/download/v1.3.1/phoneboard-v1.3.1-win32.zip

**Comment by clemy84** [comment]
Thank you will try it in the morning 👍🏻

**Comment by guidopola** [comment]
I will close this, if you still have issues comment again
