### ISSUE TITLE
iPhone 6 Plus U2402 Touch IC wrong lines

### ISSUE THREAD

**Issue by amoreger** [Phoneboard/Phoneboard#25]
Hi, I've detected some issue on this brd,

When I was working on a tuoch ic problem u2402 I saw that the NC contacts were not right. For example: C10, D10 and E10 are NC pads and in the brd are named as SAGE_TO_CUMULUS_IN<7> for C10, which corresponds to E6 as I read in the schemtics file. The brd file is showing that E6 is  SAGE_TO_CUMULUS_IN<14> which I see it even exist in the schematics file.

Plese let me know if I'm missing something.

Thanks.

**Comment by guidopola** [comment]
I have checked both the schematic and the phoneboard boardview and looks correct, are you using the correct schematic pdf?

![iphone6_schematic_meson](https://user-images.githubusercontent.com/465965/49967298-2ffd9c00-ff01-11e8-8611-08bf72e94bb0.jpeg)
