### ISSUE TITLE
iphone 6 wrong part name of WIFI components 

### ISSUE THREAD

**Issue by Sigma994** [Phoneboard/phoneboard#28]
iphone 6
Hi Wrong part name  of R5208_RF  and C5208_RF around wifi ic .  just need to be swap ich other.

**Comment by guidopola** [comment]
Can some one confirm this?

**Comment by vladwpf** [comment]
![image](https://user-images.githubusercontent.com/20670867/53528222-0dd7eb00-3afa-11e9-821c-64446099a675.png)
![image](https://user-images.githubusercontent.com/20670867/53528293-42e43d80-3afa-11e9-81ce-ba55ed454e26.png)
![image](https://user-images.githubusercontent.com/20670867/53528316-555e7700-3afa-11e9-9c90-3975ad11dc6d.png)
![image](https://user-images.githubusercontent.com/20670867/53528330-64452980-3afa-11e9-96dc-38ad9fa536ab.png)
![image](https://user-images.githubusercontent.com/20670867/53528381-89399c80-3afa-11e9-8a06-cb3fb3630cc1.png)
![image](https://user-images.githubusercontent.com/20670867/53528409-98b8e580-3afa-11e9-99cb-5ef61b113738.png)

**Comment by guidopola** [comment]
@vladwpf Thank you 👍 I'll close this as I created a new issue to put all typos etc in one place.
You can report whatever you find at #35.
