### ISSUE TITLE
Please accept BTC or other crypto as donation option.

### ISSUE THREAD

**Issue by alex8819** [Phoneboard/phoneboard#31]
Hello, if you make this application mean that you beleave in a free market, opensource, and tech, so consider to accept also crypto as a donation method ;)

**Comment by guidopola** [comment]
Thank you for the suggestion, I have added bitcoin as an option to donate :)

https://blockchain.info/address/32MGUvGdsZkDEXzv7d8xGj81JgAbuygzv3
