### ISSUE TITLE
isuue in iphone 6 wrong tracks showing

### ISSUE THREAD

**Issue by ashishkama** [Phoneboard/phoneboard#39]
pls correct it 

PMU_TO_BB_RST_R_L

**Comment by ashishkama** [comment]
![pmu_to_bb_rst_r_l](https://user-images.githubusercontent.com/12111661/51920708-f0850380-240b-11e9-95a2-17a89765be86.jpg)

**Comment by guidopola** [comment]
What's the actual issue?

**Comment by ashishkama** [comment]
ITS SHOWING WRONG PATH U CAN TRACE IT IN SCHEMANTIC

**Comment by guidopola** [comment]
Fixed, will be out in v1.4.3
