### ISSUE TITLE
BATTERY_SWI misspelled

### ISSUE THREAD

**Issue by berrytechnics** [Phoneboard/phoneboard#41]
BATTERY_SWI is misspelled BAATTERY_SWI (iphone 6+)

**Comment by berrytechnics** [comment]
![phoneboard](https://user-images.githubusercontent.com/31809859/52005527-80b85c80-248f-11e9-8f43-2b7b8e002623.png)

**Comment by guidopola** [comment]
Thank you for the report!, I'll add it to #35. If you find any other typo etc, please comment at the issue #35
