### ISSUE TITLE
Iphone 6 No Diode Values anymore

### ISSUE THREAD

**Issue by HighOnTek** [Phoneboard/phoneboard#42]
The Iphone 6 used to have diode values, but with the recent update those don't appear to be an option anymore when checking FPC connections. 

It would be super cool if there was at least an option to save our own diode values from known good boards, if they're not going to be included already with each Iphone model :)

**Comment by HighOnTek** [comment]
No problem, it finally forced me to dig out a known good Iphone 6 board and take all my own FPC measurements, saved for future reference in Google Sheets.. until you get this sorted. lol

If you need assistance with getting readings from other Iphones, I don't mind helping... it's the least I, and or the community can do for you, for all your hard work and effort.

**Comment by guidopola** [comment]
I do have some chinese pdf's with diode values. But every help are welcome :)

**Comment by HighOnTek** [comment]
Ok, no problem... not sure right now with diode readings down, but once its back up I'll try and get the ones you're missing and send them to you if you shoot me an email address (send excel or google sheets doc)... or I can post in here as an enhancement or something. Whatever works for you.

**Comment by guidopola** [comment]
If you've facebook you can contact me at fb.me/app.phoneboard 👍

**Comment by guidopola** [comment]
This is fixed and will be included in v1.4.3 release!
