### ISSUE TITLE
High Contrast Black versus Settings page

### ISSUE THREAD

**Issue by sierra2600** [Phoneboard/phoneboard#48]
This is not a high priority thing but recently I have changed the high contrast settings on my PC as I do get headaches and I noticed the text in the settings page is not readable until I temporarily change my text color settings, attached is an example...

![high contrast black vs phoneboard settings](https://user-images.githubusercontent.com/29588282/53893964-d8993480-3ff4-11e9-88cc-0b12f2a2710d.png)

(The text color is correct - white - but the background is supposed to be black when the High Contrast Black is set in Windows high contrast settings...)

**Comment by guidopola** [comment]
Hi!, I've been working on this today. This is what I have so far.
![phoneboard_highcontrast](https://user-images.githubusercontent.com/465965/53917080-81ba4c00-4042-11e9-9a2f-ce4363c773a4.png)

**Comment by guidopola** [comment]
I will close this. If you've any suggestion please feel free to comment!
