### ISSUE TITLE
Pdf schematics support

### ISSUE THREAD

**Issue by llekiar04** [Phoneboard/phoneboard#5]
![3091w1j](https://user-images.githubusercontent.com/465965/48682567-97852d80-eb87-11e8-9923-af0ee5249e15.jpg)
De antemano quiero felicitarlo por este excelente trabajo, simplemente perfecto!
Es posible integrar los esquemáticos y posibles soluciones a fallas o técnicas de medición?
No se si esta permitido hacer captura de pantalla pero en la imagen del link hago un montaje de como quedaria. Exito!

**Comment by guidopola** [comment]
Hola! Muy buena la imagen, lo hiciste de 0 al icono de esquematicos? Todavia no tiene soporte para esquematicos (pero esta en la lista!) Y lo de soluciones tenes alguna idea pensada de como podria ser?

**Comment by Edrey126** [comment]
Guido felicitaciones por tu proyecto, es genial, tiene futuro,la idea del compañero sobre los esquemáticos y las soluciones es muy buena. No dudes que te aportaremos por tu trabajo.

**Comment by guidopola** [comment]
@moondeck It has not been mentioned yet,
I know the schematics pdf are confidential files, but if the user have to download the files on their own (What i mean is we don't provide the file nor a download link) we shouldn't have any legal problems, maybe also adding an EULA to be more safe.
This feature is just a pdf viewer and we can add auto search in the pdf when the you click on a board pin for example.

**Comment by moondeck** [comment]
Yeah, exactly what i mean, that would be really cool. Not sure what formats you're using for the boards, perhaps also add support for loading external boardviews? It would surely look nice in the program :smiley:

**Comment by llekiar04** [comment]
> Hola! Muy buena la imagen, lo hiciste de 0 al icono de esquematicos? Todavia no tiene soporte para esquematicos (pero esta en la lista!) Y lo de soluciones tenes alguna idea pensada de como podria ser?

el icono lo modifique un poco basándome en otro modelo. la idea de las impedancias tambien es muy buena, la tenia en mente asi como compatibilidad de componentes posicion de los IC y lineas de reconstruccion. puedo ponerme a la orden ante cualquier colaboracion, manejo programas de vectores y conozco bien el tema. Todo sea en pro del aprendizaje :)

**Comment by DPONSEL** [comment]
How t convert pdf To BRD file(*.brd)

**Comment by moondeck** [comment]
> How t convert pdf To BRD file(*.brd)

You don't.  They are not related formats. Please don't ask unrelated or unspecific questions in GitHub issues.

**Comment by HighOnTek** [comment]
@Guidopola I love where you are going with this. Adding a feature that allows users to preset a permanent or semi permanent file path\filename.pdf to this, with auto search and locate is absolutely ingenious. I look forward to future revisions. :)

**Comment by incredulo364** [comment]
en la ultima actualizacion falto la traduccion al español
