### ISSUE TITLE
Phoneboard 1.5.0 shows white screen

### ISSUE THREAD

**Issue by ilGianfri** [Phoneboard/phoneboard#56]
Hello,
Phoneboard 1.5.0 shows a white screen on my PC and doesn't load. Sometime it will show the interface but nothing is clickable.

![image](https://user-images.githubusercontent.com/5341363/57485819-fdd44880-72ac-11e9-84bc-90fb2888a1d5.png)

Thanks

**Comment by guidopola** [comment]
Hi, Thank you for reporting, I'm aware of this issue as some people already reported it in facebook (but github is better to track issues.). It never happened to me in my box so it's strange. 

Does it always showing the white screen?
Does it shows any error message?

**Comment by ilGianfri** [comment]
Hi,
I can confirm it's fixed in 1.5.1.

Thanks
