### ISSUE TITLE
(Low Priority) Schematics Settings Page High Contrast Issue

### ISSUE THREAD

**Issue by sierra2600** [Phoneboard/phoneboard#61]
The Schematics section in Settings retains a white background while everything else changes when the HIgh Contrast settings are enabled...
![HighContrastStikesAgain!](https://user-images.githubusercontent.com/29588282/58104567-95d60a00-7baa-11e9-8e9d-14c5059e1180.png)

**Comment by guidopola** [comment]
Fixed! will be out in v1.6.1 :)
