### ISSUE TITLE
Accidental Mislabel (iPhone 6)

### ISSUE THREAD

**Issue by sierra2600** [Phoneboard/phoneboard#62]
I was poking around in the iPhone 6 board view on side B and found a capacitor labled as a resistor by the U0900 Audio Codec...
![Rnot=2C](https://user-images.githubusercontent.com/29588282/58105287-da15da00-7bab-11e9-9b0d-eeb8dbc6e637.png)

**Comment by guidopola** [comment]
Fixed, will be out in v1.6.1
