### ISSUE TITLE
phoneboard 1.6.0 bug con smartbox SXB

### ISSUE THREAD

**Issue by mastersolid** [Phoneboard/phoneboard#68]
no se puede puede grabar nombre de smartbox, tampoco se puede agregar valores sxb, solo se puede editar o borrar los valores creada por guido iphone 6s prueba. he buscado toda la forma de crear algún nuevo valor nuevo en otra linea. por favor arreglarlo para poder agregar y compartir con la comunidad.

**Comment by guidopola** [comment]
Hola @mastersolid. ¿Que sistema operativo utilizas?

**Comment by mastersolid** [comment]
windows 10 pro. en una laptop y en desktop. en ambas pasael mismo problema

**Comment by mastersolid** [comment]
arreglado phoneboard v1.6.1. gracias guido
