### ISSUE TITLE
iphone 8 /8P

### ISSUE THREAD

**Issue by holandes1969** [Phoneboard/Phoneboard#7]
hola,  primero te felicito con este proyecto,  la verdad se ve super bien.
solo una duda,   veo los iphones desde los 4 hasta los 7,   y después el X
los 8 y 8P no me aparecen.
eso es correcto y algo salió mal aquí?
aparte de así muy ansioso ver lo que va a venir,  creo es algo muy bien dar una alternativa a por ejemplo el zxw

**Comment by guidopola** [comment]
Ya eatan agregados en la version 1.2
